name = "Architects Land - Terre des Civilisations (Server)"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d22197aa06d97c2e68b6285726643489961e2932fc56ab3abe7ee4297ba9993"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
