name = "Architects Land - Terre des Civilisations (Server)"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "783185084c808658fde9d3b8104ee7fdb979df3f4a711451a5205a61b802a2e1"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
