name = "Architects Land - Terre des Civilisations (Server)"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a52add58342eeeb9c279c27755d685016406dbd581151c0fd166e16fd243890"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
