name = "Architects Land - Terre des Civilisations (Server)"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b7811156186f3c282f079bae14d85e329a0a2e3894f07ff9086183bf3230448"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
