name = "Architects Land - Terre des Civilisations (Client)"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ea6a0dfda9dbb7900f4e96b78f4b0f435d98225e0d6d0d5933615b3fb425a87"

[versions]
minecraft = "1.21"
quilt = "0.26.0"
