name = "Architects Land - Terre des Civilisations (Client)"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da5af71de11eba8224e6d87121348d087340aef7355a4aec760d49be91627a7a"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
